# Используем минимальный образ Golang
FROM golang:1.22.5

# Устанавливаем рабочую директорию для сборки
WORKDIR /app

# Копируем все файлы в контейнер
COPY . .

# Загружаем зависимости и модули
RUN go mod tidy

# Собираем приложение
RUN go build -o account-service .

# Определяем команду для запуска микросервиса
CMD ["/app/account-service"]